### ISSUE TITLE
Provide config for scala-steward

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-serialization-helper#199]
As per https://github.com/scala-steward-org/scala-steward/blob/1d020673731dbe2c73f5be233a8599ac79f70adf/docs/repo-specific-configuration.md

Some things that I can see:
* update dependencies in `examples/` which is a separate sbt project (`buildRoots`)
* run `scalafixAll` as `postUpdateHook` after scalafix sbt plugin or scalafix rules (just `organize-imports` currently) are updated
* `updatePullRequests`: maybe `always`?

**Comment by fthomas** [comment]
> run `scalafixAll` as `postUpdateHook` after scalafix sbt plugin or scalafix rules (just `organize-imports` currently) are updated

Running `scalafixAll` in case of organize-imports updates sounds interesting. I'm not familiar with organize-imports but assume that `scalafixAll` will organize the imports in projects that depend on that rule. IMO that sounds like a post-update hook that could be added the [default Scala Steward post-update hooks](https://github.com/scala-steward-org/scala-steward/blob/b48a850c1b76a09cdbbc6ceaf88d2d47f60498c3/modules/core/src/main/resources/default.scala-steward.conf#L1-L15) so that is enabled in all projects that use Scala Steward.

**Comment by PawelLipski** [comment]
> that could be added the [default Scala Steward post-update hooks](https://github.com/scala-steward-org/scala-steward/blob/b48a850c1b76a09cdbbc6ceaf88d2d47f60498c3/modules/core/src/main/resources/default.scala-steward.conf#L1-L15)

Yeah indeed, scalafix sounds like a much more common tool than e.g. `sbt-java-formatter` that's included there 😅

**Comment by aluscent** [comment]
@PawelLipski I'm on it. 🤟🏻
I was a lil bit busy these days. Let's rock.

**Comment by PawelLipski** [comment]
Gr8!

**Comment by aluscent** [comment]
@PawelLipski This is the new [.scala-steward.conf](https://github.com/aluscent/akka-serialization-helper/blob/main/.scala-steward.conf) file.
I've scheduled it to create PRs every 5 days. There's also an `@asap` tag to create PRs immediately as there was an update available, but I think it can have so much overhead for the bot.
I've also left the post-update hooks empty.
I don't exactly know your requirements, so if you need I can brief you about all of the configurations.
Also, please tell me if you need to have any dependency ignored, or if you want a specific dependency to be updated according to some version pattern.

**Comment by PawelLipski** [comment]
Gr8! could you open a PR to this repo from your fork? it's gonna be easier to comment on a PR
